site_name: Karpenter IBM Cloud Provider
site_description: Auto-scaling for Kubernetes on IBM Cloud VPC
site_author: Karpenter IBM Contributors
site_url: https://karpenter-ibm.sh/

# Repository
repo_name: kubernetes-sigs/karpenter-provider-ibm-cloud
repo_url: https://github.com/kubernetes-sigs/karpenter-provider-ibm-cloud
edit_uri: edit/main/docs/

# Copyright
copyright: |
  Copyright &copy; 2025 Karpenter IBM Cloud Provider Contributors<br>
  <a href="https://github.com/kubernetes-sigs/karpenter-provider-ibm-cloud/blob/main/LICENSE">Apache License 2.0</a>

# Configuration
docs_dir: docs/
site_dir: site/

# Exclude specific patterns from being processed
exclude_docs: |
  venv/
  mkdocs-venv/
  **/venv/**
  **/.venv/**
  node_modules/

# Navigation
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Integration Guides:
    - IBM Kubernetes Service (IKS): iks-integration.md
    - VPC Self-Managed Clusters: vpc-integration.md
  - Configuration:
    - Bootstrap Methods: bootstrap-methods.md
    - Supported CNI/CRI: supported-cni-cri.md
    - Security Considerations: security-considerations.md
  - Reference:
    - Current Limitations: limitations.md
    - Circuit Breaker Protection: circuit-breaker.md
    - Troubleshooting: troubleshooting.md
    - Nightly Builds: nightly-builds.md
  - Community:
    - Presentations & Talks: presentations.md

# Theme
theme:
  name: material
  language: en
  favicon: assets/favicon.ico
  logo: assets/logo.png
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate

# Extensions
markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
      title: On this page

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Plugins
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
  - git-revision-date-localized:
      enable_creation_date: true
      type: date
      fallback_to_build_date: true

# Extra configuration
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/kubernetes-sigs/karpenter-provider-ibm-cloud
    - icon: fontawesome/brands/docker
      link: https://github.com/kubernetes-sigs/karpenter-provider-ibm-cloud/pkgs/container/karpenter-provider-ibm-cloud
    - icon: fontawesome/brands/slack
      link: https://cloud-native.slack.com/archives/C094SDPCVLN
      name: CNCF Slack #karpenter
  version:
    provider: mike
    default: latest

# Extra CSS
extra_css:
  - assets/stylesheets/extra.css

# Extra JavaScript
extra_javascript:
  - assets/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
