{{- include "karpenter.cr.validate" . }}
{{- if and .Values.customResources.enabled .Values.customResources.nodeClass.enabled }}
apiVersion: karpenter-ibm.sh/v1alpha1
kind: IBMNodeClass
metadata:
  name: {{ .Values.customResources.nodeClass.name | default "default" }}
  labels:
    {{- include "karpenter.labels" . | nindent 4 }}
    app.kubernetes.io/component: nodeclass
spec:
  {{- toYaml .Values.customResources.nodeClass.spec | nindent 2 }}
{{- end }}
