// Code generated by MockGen. DO NOT EDIT.
// Source: ./pkg/providers/common/types/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=./pkg/providers/common/types/interfaces.go -destination=./pkg/providers/common/types/mock/interfaces_generated.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	vpcv1 "github.com/IBM/vpc-go-sdk/vpcv1"
	types "github.com/kubernetes-sigs/karpenter-provider-ibm-cloud/pkg/providers/common/types"
	gomock "go.uber.org/mock/gomock"
	v1 "k8s.io/api/core/v1"
	v10 "sigs.k8s.io/karpenter/pkg/apis/v1"
	cloudprovider "sigs.k8s.io/karpenter/pkg/cloudprovider"
)

// MockInstanceProvider is a mock of InstanceProvider interface.
type MockInstanceProvider struct {
	ctrl     *gomock.Controller
	recorder *MockInstanceProviderMockRecorder
	isgomock struct{}
}

// MockInstanceProviderMockRecorder is the mock recorder for MockInstanceProvider.
type MockInstanceProviderMockRecorder struct {
	mock *MockInstanceProvider
}

// NewMockInstanceProvider creates a new mock instance.
func NewMockInstanceProvider(ctrl *gomock.Controller) *MockInstanceProvider {
	mock := &MockInstanceProvider{ctrl: ctrl}
	mock.recorder = &MockInstanceProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInstanceProvider) EXPECT() *MockInstanceProviderMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockInstanceProvider) Create(ctx context.Context, nodeClaim *v10.NodeClaim, instanceTypes []*cloudprovider.InstanceType) (*v1.Node, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, nodeClaim, instanceTypes)
	ret0, _ := ret[0].(*v1.Node)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockInstanceProviderMockRecorder) Create(ctx, nodeClaim, instanceTypes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockInstanceProvider)(nil).Create), ctx, nodeClaim, instanceTypes)
}

// Delete mocks base method.
func (m *MockInstanceProvider) Delete(ctx context.Context, node *v1.Node) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, node)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockInstanceProviderMockRecorder) Delete(ctx, node any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockInstanceProvider)(nil).Delete), ctx, node)
}

// Get mocks base method.
func (m *MockInstanceProvider) Get(ctx context.Context, providerID string) (*v1.Node, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, providerID)
	ret0, _ := ret[0].(*v1.Node)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockInstanceProviderMockRecorder) Get(ctx, providerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockInstanceProvider)(nil).Get), ctx, providerID)
}

// GetFresh mocks base method.
func (m *MockInstanceProvider) GetFresh(ctx context.Context, providerID string) (*v1.Node, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFresh", ctx, providerID)
	ret0, _ := ret[0].(*v1.Node)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFresh indicates an expected call of GetFresh.
func (mr *MockInstanceProviderMockRecorder) GetFresh(ctx, providerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFresh", reflect.TypeOf((*MockInstanceProvider)(nil).GetFresh), ctx, providerID)
}

// List mocks base method.
func (m *MockInstanceProvider) List(ctx context.Context) ([]*v1.Node, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*v1.Node)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockInstanceProviderMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockInstanceProvider)(nil).List), ctx)
}

// ListFresh mocks base method.
func (m *MockInstanceProvider) ListFresh(ctx context.Context, claims []*v10.NodeClaim, nodes []*v1.Node) ([]*v1.Node, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFresh", ctx, claims, nodes)
	ret0, _ := ret[0].([]*v1.Node)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFresh indicates an expected call of ListFresh.
func (mr *MockInstanceProviderMockRecorder) ListFresh(ctx, claims, nodes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFresh", reflect.TypeOf((*MockInstanceProvider)(nil).ListFresh), ctx, claims, nodes)
}

// MockVPCInstanceProvider is a mock of VPCInstanceProvider interface.
type MockVPCInstanceProvider struct {
	ctrl     *gomock.Controller
	recorder *MockVPCInstanceProviderMockRecorder
	isgomock struct{}
}

// MockVPCInstanceProviderMockRecorder is the mock recorder for MockVPCInstanceProvider.
type MockVPCInstanceProviderMockRecorder struct {
	mock *MockVPCInstanceProvider
}

// NewMockVPCInstanceProvider creates a new mock instance.
func NewMockVPCInstanceProvider(ctrl *gomock.Controller) *MockVPCInstanceProvider {
	mock := &MockVPCInstanceProvider{ctrl: ctrl}
	mock.recorder = &MockVPCInstanceProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVPCInstanceProvider) EXPECT() *MockVPCInstanceProviderMockRecorder {
	return m.recorder
}

// CleanupPending mocks base method.
func (m *MockVPCInstanceProvider) CleanupPending(arg0 context.Context, arg1 *v10.NodeClaim) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanupPending", arg0, arg1)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CleanupPending indicates an expected call of CleanupPending.
func (mr *MockVPCInstanceProviderMockRecorder) CleanupPending(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanupPending", reflect.TypeOf((*MockVPCInstanceProvider)(nil).CleanupPending), arg0, arg1)
}

// Create mocks base method.
func (m *MockVPCInstanceProvider) Create(ctx context.Context, nodeClaim *v10.NodeClaim, instanceTypes []*cloudprovider.InstanceType) (*v1.Node, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, nodeClaim, instanceTypes)
	ret0, _ := ret[0].(*v1.Node)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockVPCInstanceProviderMockRecorder) Create(ctx, nodeClaim, instanceTypes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockVPCInstanceProvider)(nil).Create), ctx, nodeClaim, instanceTypes)
}

// Delete mocks base method.
func (m *MockVPCInstanceProvider) Delete(ctx context.Context, node *v1.Node) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, node)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockVPCInstanceProviderMockRecorder) Delete(ctx, node any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockVPCInstanceProvider)(nil).Delete), ctx, node)
}

// Get mocks base method.
func (m *MockVPCInstanceProvider) Get(ctx context.Context, providerID string) (*v1.Node, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, providerID)
	ret0, _ := ret[0].(*v1.Node)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockVPCInstanceProviderMockRecorder) Get(ctx, providerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockVPCInstanceProvider)(nil).Get), ctx, providerID)
}

// GetFresh mocks base method.
func (m *MockVPCInstanceProvider) GetFresh(ctx context.Context, providerID string) (*v1.Node, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFresh", ctx, providerID)
	ret0, _ := ret[0].(*v1.Node)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFresh indicates an expected call of GetFresh.
func (mr *MockVPCInstanceProviderMockRecorder) GetFresh(ctx, providerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFresh", reflect.TypeOf((*MockVPCInstanceProvider)(nil).GetFresh), ctx, providerID)
}

// List mocks base method.
func (m *MockVPCInstanceProvider) List(ctx context.Context) ([]*v1.Node, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*v1.Node)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockVPCInstanceProviderMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockVPCInstanceProvider)(nil).List), ctx)
}

// ListFresh mocks base method.
func (m *MockVPCInstanceProvider) ListFresh(ctx context.Context, claims []*v10.NodeClaim, nodes []*v1.Node) ([]*v1.Node, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFresh", ctx, claims, nodes)
	ret0, _ := ret[0].([]*v1.Node)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFresh indicates an expected call of ListFresh.
func (mr *MockVPCInstanceProviderMockRecorder) ListFresh(ctx, claims, nodes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFresh", reflect.TypeOf((*MockVPCInstanceProvider)(nil).ListFresh), ctx, claims, nodes)
}

// UpdateTags mocks base method.
func (m *MockVPCInstanceProvider) UpdateTags(ctx context.Context, providerID string, tags map[string]string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTags", ctx, providerID, tags)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTags indicates an expected call of UpdateTags.
func (mr *MockVPCInstanceProviderMockRecorder) UpdateTags(ctx, providerID, tags any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTags", reflect.TypeOf((*MockVPCInstanceProvider)(nil).UpdateTags), ctx, providerID, tags)
}

// ValidateLaunchTarget mocks base method.
func (m *MockVPCInstanceProvider) ValidateLaunchTarget(arg0 context.Context, arg1 *v10.NodeClaim) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateLaunchTarget", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateLaunchTarget indicates an expected call of ValidateLaunchTarget.
func (mr *MockVPCInstanceProviderMockRecorder) ValidateLaunchTarget(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateLaunchTarget", reflect.TypeOf((*MockVPCInstanceProvider)(nil).ValidateLaunchTarget), arg0, arg1)
}

// VerifyLaunchInstance mocks base method.
func (m *MockVPCInstanceProvider) VerifyLaunchInstance(arg0 context.Context, arg1 *v10.NodeClaim) (*vpcv1.Instance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyLaunchInstance", arg0, arg1)
	ret0, _ := ret[0].(*vpcv1.Instance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyLaunchInstance indicates an expected call of VerifyLaunchInstance.
func (mr *MockVPCInstanceProviderMockRecorder) VerifyLaunchInstance(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyLaunchInstance", reflect.TypeOf((*MockVPCInstanceProvider)(nil).VerifyLaunchInstance), arg0, arg1)
}

// VerifyLaunchNetworkAddresses mocks base method.
func (m *MockVPCInstanceProvider) VerifyLaunchNetworkAddresses(arg0 context.Context, arg1 *v10.NodeClaim, arg2 *vpcv1.Instance) ([]string, []string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyLaunchNetworkAddresses", arg0, arg1, arg2)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].([]string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// VerifyLaunchNetworkAddresses indicates an expected call of VerifyLaunchNetworkAddresses.
func (mr *MockVPCInstanceProviderMockRecorder) VerifyLaunchNetworkAddresses(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyLaunchNetworkAddresses", reflect.TypeOf((*MockVPCInstanceProvider)(nil).VerifyLaunchNetworkAddresses), arg0, arg1, arg2)
}

// MockIKSWorkerPoolProvider is a mock of IKSWorkerPoolProvider interface.
type MockIKSWorkerPoolProvider struct {
	ctrl     *gomock.Controller
	recorder *MockIKSWorkerPoolProviderMockRecorder
	isgomock struct{}
}

// MockIKSWorkerPoolProviderMockRecorder is the mock recorder for MockIKSWorkerPoolProvider.
type MockIKSWorkerPoolProviderMockRecorder struct {
	mock *MockIKSWorkerPoolProvider
}

// NewMockIKSWorkerPoolProvider creates a new mock instance.
func NewMockIKSWorkerPoolProvider(ctrl *gomock.Controller) *MockIKSWorkerPoolProvider {
	mock := &MockIKSWorkerPoolProvider{ctrl: ctrl}
	mock.recorder = &MockIKSWorkerPoolProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIKSWorkerPoolProvider) EXPECT() *MockIKSWorkerPoolProviderMockRecorder {
	return m.recorder
}

// Cleanup mocks base method.
func (m *MockIKSWorkerPoolProvider) Cleanup(arg0 context.Context, arg1 *v10.NodeClaim) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cleanup", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Cleanup indicates an expected call of Cleanup.
func (mr *MockIKSWorkerPoolProviderMockRecorder) Cleanup(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cleanup", reflect.TypeOf((*MockIKSWorkerPoolProvider)(nil).Cleanup), arg0, arg1)
}

// ConfirmGone mocks base method.
func (m *MockIKSWorkerPoolProvider) ConfirmGone(arg0 context.Context, arg1 *v10.NodeClaim) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfirmGone", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConfirmGone indicates an expected call of ConfirmGone.
func (mr *MockIKSWorkerPoolProviderMockRecorder) ConfirmGone(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfirmGone", reflect.TypeOf((*MockIKSWorkerPoolProvider)(nil).ConfirmGone), arg0, arg1)
}

// Create mocks base method.
func (m *MockIKSWorkerPoolProvider) Create(ctx context.Context, nodeClaim *v10.NodeClaim, instanceTypes []*cloudprovider.InstanceType) (*v1.Node, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, nodeClaim, instanceTypes)
	ret0, _ := ret[0].(*v1.Node)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockIKSWorkerPoolProviderMockRecorder) Create(ctx, nodeClaim, instanceTypes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIKSWorkerPoolProvider)(nil).Create), ctx, nodeClaim, instanceTypes)
}

// CreatePool mocks base method.
func (m *MockIKSWorkerPoolProvider) CreatePool(ctx context.Context, clusterID string, request *types.CreatePoolRequest) (*types.WorkerPool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePool", ctx, clusterID, request)
	ret0, _ := ret[0].(*types.WorkerPool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePool indicates an expected call of CreatePool.
func (mr *MockIKSWorkerPoolProviderMockRecorder) CreatePool(ctx, clusterID, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePool", reflect.TypeOf((*MockIKSWorkerPoolProvider)(nil).CreatePool), ctx, clusterID, request)
}

// Delete mocks base method.
func (m *MockIKSWorkerPoolProvider) Delete(ctx context.Context, node *v1.Node) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, node)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockIKSWorkerPoolProviderMockRecorder) Delete(ctx, node any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIKSWorkerPoolProvider)(nil).Delete), ctx, node)
}

// DeletePool mocks base method.
func (m *MockIKSWorkerPoolProvider) DeletePool(ctx context.Context, clusterID, poolID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePool", ctx, clusterID, poolID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePool indicates an expected call of DeletePool.
func (mr *MockIKSWorkerPoolProviderMockRecorder) DeletePool(ctx, clusterID, poolID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePool", reflect.TypeOf((*MockIKSWorkerPoolProvider)(nil).DeletePool), ctx, clusterID, poolID)
}

// Get mocks base method.
func (m *MockIKSWorkerPoolProvider) Get(ctx context.Context, providerID string) (*v1.Node, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, providerID)
	ret0, _ := ret[0].(*v1.Node)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockIKSWorkerPoolProviderMockRecorder) Get(ctx, providerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockIKSWorkerPoolProvider)(nil).Get), ctx, providerID)
}

// GetFresh mocks base method.
func (m *MockIKSWorkerPoolProvider) GetFresh(ctx context.Context, providerID string) (*v1.Node, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFresh", ctx, providerID)
	ret0, _ := ret[0].(*v1.Node)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFresh indicates an expected call of GetFresh.
func (mr *MockIKSWorkerPoolProviderMockRecorder) GetFresh(ctx, providerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFresh", reflect.TypeOf((*MockIKSWorkerPoolProvider)(nil).GetFresh), ctx, providerID)
}

// GetPool mocks base method.
func (m *MockIKSWorkerPoolProvider) GetPool(ctx context.Context, clusterID, poolID string) (*types.WorkerPool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPool", ctx, clusterID, poolID)
	ret0, _ := ret[0].(*types.WorkerPool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPool indicates an expected call of GetPool.
func (mr *MockIKSWorkerPoolProviderMockRecorder) GetPool(ctx, clusterID, poolID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPool", reflect.TypeOf((*MockIKSWorkerPoolProvider)(nil).GetPool), ctx, clusterID, poolID)
}

// List mocks base method.
func (m *MockIKSWorkerPoolProvider) List(ctx context.Context) ([]*v1.Node, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*v1.Node)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockIKSWorkerPoolProviderMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockIKSWorkerPoolProvider)(nil).List), ctx)
}

// ListFresh mocks base method.
func (m *MockIKSWorkerPoolProvider) ListFresh(ctx context.Context, claims []*v10.NodeClaim, nodes []*v1.Node) ([]*v1.Node, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFresh", ctx, claims, nodes)
	ret0, _ := ret[0].([]*v1.Node)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFresh indicates an expected call of ListFresh.
func (mr *MockIKSWorkerPoolProviderMockRecorder) ListFresh(ctx, claims, nodes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFresh", reflect.TypeOf((*MockIKSWorkerPoolProvider)(nil).ListFresh), ctx, claims, nodes)
}

// ListPools mocks base method.
func (m *MockIKSWorkerPoolProvider) ListPools(ctx context.Context, clusterID string) ([]*types.WorkerPool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPools", ctx, clusterID)
	ret0, _ := ret[0].([]*types.WorkerPool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPools indicates an expected call of ListPools.
func (mr *MockIKSWorkerPoolProviderMockRecorder) ListPools(ctx, clusterID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPools", reflect.TypeOf((*MockIKSWorkerPoolProvider)(nil).ListPools), ctx, clusterID)
}

// PrepareLegacyRetirement mocks base method.
func (m *MockIKSWorkerPoolProvider) PrepareLegacyRetirement(arg0 context.Context, arg1 *v10.NodeClaim) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PrepareLegacyRetirement", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// PrepareLegacyRetirement indicates an expected call of PrepareLegacyRetirement.
func (mr *MockIKSWorkerPoolProviderMockRecorder) PrepareLegacyRetirement(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrepareLegacyRetirement", reflect.TypeOf((*MockIKSWorkerPoolProvider)(nil).PrepareLegacyRetirement), arg0, arg1)
}

// ResizePool mocks base method.
func (m *MockIKSWorkerPoolProvider) ResizePool(ctx context.Context, clusterID, poolID string, newSize int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResizePool", ctx, clusterID, poolID, newSize)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResizePool indicates an expected call of ResizePool.
func (mr *MockIKSWorkerPoolProviderMockRecorder) ResizePool(ctx, clusterID, poolID, newSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResizePool", reflect.TypeOf((*MockIKSWorkerPoolProvider)(nil).ResizePool), ctx, clusterID, poolID, newSize)
}
